#ifndef DEBUG_H_
#define DEBUG_H_

typedef enum SABUGO_ERROR
{
    NO_ERROR = 0,
    CORE_GLFW_INIT_ERROR,
    CORE_GLFW_NO_WINDOW_HANDLE_ERROR,
    RENDERER_INIT_GRAPHICAL_CONTEXT_GLEW_INIT_ERROR

} SABUGO_ERROR;

#endif

